[package]
name = "angelscript-modules"
version = "0.1.0"
edition = "2024"

[dependencies]
angelscript-core = { path = "../angelscript-core" }
angelscript-module = { path = "../angelscript-module" }
angelscript-ffi = { path = "../angelscript-ffi" }
ordered-float.workspace = true
