[package]
name = "angelscript-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
angelscript-core.workspace = true
bumpalo.workspace = true
thiserror.workspace = true
profiling = { workspace = true, optional = true }

[features]
default = []
profiling = ["dep:profiling"]
