[package]
name = "angelscript-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
angelscript-core = { path = "../angelscript-core" }
angelscript-registry = { path = "../angelscript-registry" }
angelscript-parser = { path = "../angelscript-parser" }
rustc-hash.workspace = true
